### PR TITLE
Grammar updates

### PR DESCRIPTION
**Pull request by AntoineBalaine**
Hello,

I added a few tokens to your grammar in my fork, maybe they could be useful to you?

Amongst the main changes that I did:

- `chords` were renamed to annotations - rationale being that the `<abc music>"some text"<abc music>` format doesn't exclusively contain chord symbols.
- I added the following properties: 

```
accidentalsAndOctaves
annotations
bar
note-rhythm
ornaments 
rhythm
symbols
ties
voice
words
```

I also included a yaml file, for reference, in case you like the syntax? I'll revert that file based on your feedback.

Also, if you're interested, I have a [peg grammar](https://github.com/AntoineBalaine/abc_pest_grammar) that could be ported to textMate - it would probably be painful to do, but would offer the advantage of covering most of the ABC standard.

Here's the current looks of the syntax:
Screenshot_20221121_190511

### CODE REVIEW

**Comment by alensiljak** [comment]
Hey, Antoine! Thanks a lot for this addition! This looks great. I will publish a new version with these changes. 

I see you are building an ABC parser in Rust. I'm a fresh Rustacean and will enjoy following that project! The more tools, the better. I can also test it on my tunes and provide some feedback, depending on what your end-goal is.

~~The only thing I've noticed with these changes, tested on my sheets, is that the Meter does not include textual marks, i.e.~~
image

Edit: added inline meter

I'll accept the changes as-is since it is a decent step forward. Minor improvements can also be done incrementally.
The source code looks much more readable now!

Some quick ideas, since you raised the topic... 
~~1.) parts names might be distinguished by colour~~
image

Edit: done

~~2.) It would be great to have `%` comments and `%%` instructions separated by a different shade, perhaps~~
image

Edit: done

Anyways, these would be nice-to-haves. Thanks again!

**Comment by alensiljak** [comment]
Right, the `%%` instructions were blue previously

image

Edit: I see that there's a definition for instruction but am not sure what decides the line colour.

Edit 2: I've fixed this one

**Comment by alensiljak** [comment]
Annotations don't seem to be as precise:

image

vs

**Comment by alensiljak** [comment]
The text et the beginning not recognized:

image

Edit: This was also the case before, it seems.

**Comment by AntoineBalaine** [comment]
This is fantastic! I'm glad you liked the update! 
For the peg parser - I'm also very new into the rust game, so it might take some time before I'm able to actually get something out of it. PRs welcome!

My goal for it is to target web assembly and use the parser to add some code actions to edit the music (transpose, change rhythms, add some macros for arranging, etc.). 
I currently have a janky version of the projected-functionality written in TS in [a fork of your extension](https://github.com/AntoineBalaine/abcjs-vscode/tree/abc-editing-macros) that uses my [editing macros](https://github.com/AntoineBalaine/abc-editing-macros). It's been a fun project, but I really need to be parsing ABC scores into an AST if this thing is to ever get off the ground - thus the switch to pest's rust parser.
The formatter and the arranging automation (supposed to help build arrangement routines) are broken atm, but the transpose and note-length functions are working:

Peek 2022-11-22 21-01
Peek 2022-11-22 21-03

**Comment by alensiljak** [comment]
Oh, that's really cool! Wasm is obviously the future and Rust might be a great way to get there. Would you be interested to join the abcjs-music organization? I mean, there's nothing really formal. We all happen to work on related stuff in our spare time.

The thing with the macros seems really interesting. I think Paul has some of it built-in in abcjs but it might be interesting to have it in a separate module, or whatever. I was just reading about wasm interop / component model and that's will provide some interesting options. But even current wasm functionality is great and we could start leveraging it.

Adding @paulrosen as this might be even more interesting for him!

**Comment by AntoineBalaine** [comment]
Yes please, I'd love to be part of the organization! I'll reach out via email directly so we can keep this conversation going.

**Pull request merged**
